config/routes.rb
Rails.application.routes.draw do
  resources :services
  resources :roughs
  resources :trims
  resources :people
  resources :houses
  get 'home/index'
  root 'houses#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/person.rb
class Person < ApplicationRecord
    validates :fname, :lname, :email, presence: true
    validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }

    def full_name
        "#{fname} #{lname}"
      end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people or /people.json
  def index
    if params[:search]
      search_people
    else
      @people = Person.order(params[:sort])
    end
  end
  
  def search_people
    if @people= Person.all.find{|person| person.fname.include?(params[:search])}
      redirect_to person_path(@person)
    end
  end
  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to person_url(@person), notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to person_url(@person), notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:fname, :lname, :email)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_with(model: person) do |form| %>
  <% if person.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :fname,"First Name", style: "display: block" %>
    <%= form.text_field :fname %>
  </div>

  <div>
    <%= form.label :lname,"Last Name", style: "display: block" %>
    <%= form.text_field :lname %>
  </div>

  <div>
    <%= form.label :email,"Email", style: "display: block" %>
    <%= form.text_field :email %>
  </div>
<br><br>
  <div>
    <%= form.submit :"Save", class:"btn btn-outline-dark btn-lg"%>
  </div>
<% end %>

app/views/people/_person.html.erb
<div id="<%= dom_id person %>">
  <p>
    <strong>First Name:</strong>
    <%= person.fname %>
  </p>

  <p>
    <strong>Last Name:</strong>
    <%= person.lname %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= person.email %>
  </p>

</div>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Show this person", @person, class:"btn btn-outline-dark btn-sm" %> |
  <%= link_to "Back to people", people_path, class:"btn btn-outline-dark btn-sm" %>
  <br><br>
  <%= button_to "Destroy this person", @person, class:"btn btn-outline-danger btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %><br>
</div>

app/views/people/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>People</h1>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="table-responsive fixed-table-body">
        <table class="table table-striped table-hover">
        <thead>
            <tr class="table-light">  
              <th><%= link_to "First Name", :sort => "fname"%></th>
              <th><%= link_to "Last Name", :sort => "lname"%></th>
              <th>Email</th>
              <th colspan="2"></th>
            </tr>
          </thead>
          <tbody>
            <% @people.each do |person| %>
              <tr>
                <td><%= person.fname%></td>
                <td><%= person.lname%></td>
                <td><%= person.email%></td>
                <td><%= link_to 'Show', person %></td>
                <td><%= link_to 'Edit', edit_person_path(person) %></td>
              </tr>
            <% end %>
        </table>
      </div>
    </div>
  </div>
</div>


<%= link_to "New person", new_person_path, class:"btn btn-outline-dark btn-sm" %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Back to people", people_path, class:"btn btn-outline-dark btn-sm" %>
</div>

app/views/people/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @person %>

<div>
  <%= link_to "Edit this person", edit_person_path(@person), class:"btn btn-outline-dark btn-sm" %> |
  <%= link_to "Back to people", people_path, class:"btn btn-outline-dark btn-sm" %>
</div>