config/routes.rb
Rails.application.routes.draw do
  resources :services
  resources :roughs
  resources :trims
  resources :people
  resources :houses
  get 'home/index'
  root 'houses#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/trim.rb
class Trim < ApplicationRecord
  belongs_to :house
  
  validates :content, presence: true
  has_one_attached :picture

  def has_pic(condtion)
    if condtion
    "\u2705"
    else
    "\u274C"
    end
  end
end

app/controllers/trims_controller.rb
class TrimsController < ApplicationController
  before_action :set_trim, only: %i[ show edit update destroy ]
  # GET /trims or /trims.json
  def index
    @trims = Trim.all
  end

  # GET /trims/1 or /trims/1.json
  def show
  end

  # GET /trims/new
  def new
    @trim = Trim.new
  end

  # GET /trims/1/edit
  def edit
  end

  # POST /trims or /trims.json
  def create
    @trim = Trim.new(trim_params)

    respond_to do |format|
      if @trim.save
        format.html { redirect_to trim_url(@trim), notice: "Trim was successfully created." }
        format.json { render :show, status: :created, location: @trim }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trim.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trims/1 or /trims/1.json
  def update
    respond_to do |format|
      if @trim.update(trim_params)
        format.html { redirect_to trim_url(@trim), notice: "Trim was successfully updated." }
        format.json { render :show, status: :ok, location: @trim }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trim.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trims/1 or /trims/1.json
  def destroy
    @trim.destroy

    respond_to do |format|
      format.html { redirect_to trims_url, notice: "Trim was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trim
      @trim = Trim.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trim_params
      params.require(:trim).permit(:content, :house_id,:picture, :completed, :notes)
    end
end

app/helpers/trims_helper.rb
module TrimsHelper
end

app/views/trims/_form.html.erb
<%= form_with(model: trim) do |form| %>
  <% if trim.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(trim.errors.count, "error") %> prohibited this trim from being saved:</h2>

      <ul>
        <% trim.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "container">
    <div>
      <%= form.label :house_id,"Address", style: "display: block" %>
      <%= collection_select( :trim, :house_id, House.all, :id, :address, include_blank: 'None') %>
    </div>
    <br>
    <div class = "row">
      <div class = "col">
        <div>
          <%= form.label :picture,"Upload Photo", style: "display: block" %>
          <%= form.file_field :picture %>
        </div>
        <br>
        <div>
          <%= form.label :Content, style: "display: block" %>
          <%= form.text_field :content %>
        </div>
        <br><br>
      </div>
      <div class = "col">
        <div>
          <%= form.label :completed,"Who Completed This", style: "display: block" %>
          <%= collection_select( :trim, :completed, Person.all, :id, :full_name, include_blank: 'None') %>
        </div>
        <br>
        <div>
          <%= form.label :Notes, style: "display: block" %>
          <%= form.text_field :notes %>
        </div>
      </div>
    </div>
    <div>
      <br>
      <%= form.submit :"Save", class:"btn btn-outline-dark btn-lg"%>
    </div>
  </div>
<% end %>

app/views/trims/_trim.html.erb
<div id="<%= dom_id trim %>">
  <div class="card" style="width: 18rem;">
    Last Update: 
    <%= trim.updated_at.in_time_zone('America/Chicago').strftime("%m/%d/%Y %I:%M%p")%><br>
    <% if trim.picture.attached? %>
      <img class="card-img-top" src="<%=(url_for(trim.picture))%>">
      <a href="<%=(url_for(trim.picture))%>"target="_blank">View Full Picture</a>
      <div class="card-body">
        <p class = "card-text">
        <%= trim.content%><br>
        </p>
        <p class = "card-text">
          <% if Person.where(id: trim.completed).exists?%>
            <%= trim.notes%> - 
            <%= Person.where(id: trim.completed).last.full_name%>
          <%else%>
            Note:
            <%= trim.notes%><br>
            <%= link_to "In Progess", edit_trim_path(trim) %>
          <%end%>
        </p>
      </div>
    <%else%>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><%= trim.content%></li>
        <li class="list-group-item">
        <% if Person.where(id: trim.completed).exists?%>
          <%= trim.notes%> - 
          <%= Person.where(id: trim.completed).last.full_name%>
        <%else%>
          Note:
          <%= trim.notes%><br>
          <%= link_to "In Progess", edit_trim_path(trim) %>
        <%end%>
        </li>
        
      </ul>
    <%end%>
  </div>
  <br>
</div>

app/views/trims/edit.html.erb
<h1>Editing trim</h1>

<%= render "form", trim: @trim %>

<br>

<div>
  <%= link_to "Show this trim", @trim, class:"btn btn-outline-dark btn-sm" %> |
  <%= link_to "Back", houses_path, class:"btn btn-outline-dark btn-sm"  %>
  <br>
  <%= button_to "Destroy this trim", @trim, class:"btn btn-outline-danger btn-sm", method: :delete %>
</div>

app/views/trims/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Rough In</h1>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="table-responsive fixed-table-body">
        <table class="table table-striped table-hover">
          <thead>
            <tr class="table-light">  
              <th>Address</th>
              <th>Content</th>
              <th>Notes</th>
              <th>Picture</th>
              <th colspan="2"></th>
            </tr>
          </thead>
          <tbody>
          <% Rough.all.each do |rough| %>
            <tr>
              <td><%= House.where(id: rough.house_id).last.address%></td>
              <td><%= rough.content%></td>
              <td><%= rough.notes%></td>
              <td><%= rough.has_pic(rough.picture?) %></td>
              <td><%= link_to 'Show',rough %></td>
              <td><%= link_to 'Edit', edit_rough_path(rough) %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
  <%= link_to "New Rough In", new_rough_path, class:"btn btn-outline-dark btn-sm" %>
  <br>
  <h1>Trim Out</h1>
  <div class="row">
    <div class="col-md-12">
      <div class="table-responsive fixed-table-body">
        <table class="table table-striped table-hover">
          <thead>
            <tr class="table-light">  
              <th>Address</th>
              <th>Content</th>
              <th>Notes</th>
              <th>Picture</th>
              <th colspan="2"></th>
            </tr>
          </thead>
          <tbody>
          <% @trims.each do |trim| %>
            <tr>
              <td><%= House.where(id: trim.house_id).last.address%></td>
              <td><%= trim.content%></td>
              <td><%= trim.notes%></td>
              <td><%= trim.has_pic(trim.picture?) %></td>
              <td><%= link_to 'Show', trim %></td>
              <td><%= link_to 'Edit', edit_trim_path(trim) %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
  <%= link_to "New Trim Out", new_trim_path, class:"btn btn-outline-dark btn-sm" %>
  <br>
  <h1>Service Calls</h1>
  <div class="row">
    <div class="col-md-12">
      <div class="table-responsive fixed-table-body">
        <table class="table table-striped table-hover">
          <thead>
            <tr class="table-light">  
              <th>Address</th>
              <th>Content</th>
              <th>Notes</th>
              <th>Picture</th>
              <th colspan="2"></th>
            </tr>
          </thead>
          <tbody>
          <% Service.all.each do |service| %>
            <tr>
              <td><%= House.where(id: service.house_id).last.address%></td>
              <td><%= service.content%></td>
              <td><%= service.notes%></td>
              <td><%= service.has_pic(service.picture?) %></td>
              <td><%= link_to 'Show', service %></td>
              <td><%= link_to 'Edit', edit_service_path(service) %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
<%= link_to "New Service Call", new_service_path, class:"btn btn-outline-dark btn-sm" %>
</div>

app/views/trims/new.html.erb
<h1>New trim</h1>

<%= render "form", trim: @trim %>

<br>

<div>
  <%= link_to "Back", houses_path, class:"btn btn-outline-dark btn-sm"  %>
</div>

app/views/trims/show.html.erb
<p style="color: green"><%= notice %></p>
<h1>
<%= House.where(id: @trim.house_id).last.address%>
</h1>
<%= render @trim %>

<div>
  <%= link_to "New Trim Out", new_trim_path, class:"btn btn-outline-dark btn-sm" %> | 
  <%= link_to "Edit this trim", edit_trim_path(@trim), class:"btn btn-outline-dark btn-sm" %> |
  <%= link_to "Back", houses_path, class:"btn btn-outline-dark btn-sm"  %>
</div>