config/routes.rb
Rails.application.routes.draw do
  resources :services
  resources :roughs
  resources :trims
  resources :people
  resources :houses
  get 'home/index'
  root 'houses#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Electric City", houses_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to 'Addresses', houses_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'People', people_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Punch List', trims_path, class:"nav-link"%>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <%= form_tag(houses_path, method: :get ) do %>
          <%= text_field_tag(:search, params[:search])%>
          <%= submit_tag ("Search"),class: "btn btn-outline-success my-2 my-sm-0" %>
        <% end %>
        
      </form>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Home</h1>
<h2>I don't know how you got here but please leave... you're making me nervous</h2>